{
 "title": "Medic / Cluster cost estimate",
 "tags": [
  "cost",
  "medic",
  "link"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cost estimation $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "Namespace cost estimate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (\n          sum_over_time(\n            (\n                    label_replace(\n                      (\n                          (\n                              avg by (container, node, namespace, pod) (container_memory_allocation_bytes{namespace=~\"$namespace\"})\n                            * on (node) group_left ()\n                              avg by (node) (node_ram_hourly_cost)\n                          )\n                        /\n                          (1024 * 1024 * 1024)\n                      ),\n                      \"type\",\n                      \"ram\",\n                      \"\",\n                      \"\"\n                    )\n                  or\n                    label_replace(\n                      (\n                          avg by (container, node, namespace, pod) (container_cpu_allocation{namespace=~\"$namespace\"})\n                        * on (node) group_left ()\n                          avg by (node) (node_cpu_hourly_cost)\n                      ),\n                      \"type\",\n                      \"cpu\",\n                      \"\",\n                      \"\"\n                    )\n                or\n                  label_replace(\n                    (\n                        avg by (container, node, namespace, pod) (container_gpu_allocation{namespace=~\"$namespace\"})\n                      * on (node) group_left ()\n                        avg by (node) (node_gpu_hourly_cost)\n                    ),\n                    \"type\",\n                    \"gpu\",\n                    \"\",\n                    \"\"\n                  )\n              or\n                label_replace(\n                  (\n                      (\n                          avg by (persistentvolume, namespace, pod) (pod_pvc_allocation{namespace=~\"$namespace\"})\n                        * on (persistentvolume) group_left ()\n                          avg by (persistentvolume) (pv_hourly_cost)\n                      )\n                    /\n                      (1024 * 1024 * 1024)\n                  ),\n                  \"type\",\n                  \"storage\",\n                  \"\",\n                  \"\"\n                )\n            )[30d:5m]\n          )\n        /\n          scalar(count_over_time(vector(1)[30d:5m]))\n      * 24 * 30\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per container",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "  sum by (type, namespace, container) (\n          sum_over_time(\n            (\n                    label_replace(\n                      (\n                          avg by (container, node, namespace, pod) (container_cpu_allocation{namespace=~\"$namespace\"})\n                        * on (node) group_left ()\n                          avg by (node) (node_cpu_hourly_cost)\n                      ),\n                      \"type\",\n                      \"cpu\",\n                      \"\",\n                      \"\"\n                    )\n            )[30d:5m]\n          )\n        /\n          scalar(count_over_time(vector(1)[30d:5m]))\n      * 24 * 30\n  )\n",
     "legendFormat": "cpu"
    },
    {
     "expr": "  sum by (type, namespace, container) (\n          sum_over_time(\n            (\n                    label_replace(\n                      (\n                          (\n                              avg by (container, node, namespace, pod) (container_memory_allocation_bytes{namespace=~\"$namespace\"})\n                            * on (node) group_left ()\n                              avg by (node) (node_ram_hourly_cost)\n                          )\n                        /\n                          (1024 * 1024 * 1024)\n                      ),\n                      \"type\",\n                      \"ram\",\n                      \"\",\n                      \"\"\n                    )\n            )[30d:5m]\n          )\n        /\n          scalar(count_over_time(vector(1)[30d:5m]))\n      * 24 * 30\n  )\n",
     "legendFormat": "ram"
    }
   ]
  },
  {
   "title": "Per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (namespace,instance,container) * on(instance) group_left() (\n\t\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024\n\t\t\t\t+ on(node,instance_type) group_left()\n\t\t\t\t\tlabel_replace\n\t\t\t\t\t(\n\t\t\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t\t\t) * 0\n\t\t\t) + sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (namespace,instance,container) * on(instance) group_left() (\n\t  \t\t\tnode_cpu_hourly_cost{} + on(node,instance_type) group_left()\n\t\t  \t\t\tlabel_replace\n\t\t  \t\t\t(\n\t\t  \t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t  \t\t\t) * 0\n\t\t  \t)) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Total cluster estimation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost) by (node) * 24 * 30\n)",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(\n  avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * 24 * 30\n)",
     "legendFormat": "ram"
    },
    {
     "expr": "sum(avg(pv_hourly_cost) by (persistentvolume) * 24 * 30 * avg(kube_persistentvolume_capacity_bytes) by (persistentvolume) / 1024 / 1024 / 1024) \n+\n(sum(sum(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}) by (instance) / 1024 / 1024 / 1024) * on() vector(0))",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "Total Monthly Cost",
   "type": "stat",
   "description": "Sum of compute, memory, storage and network costs.",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Compute\nsum(\n  avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost) by (node) * 24 * 30 +\n  avg(node_gpu_hourly_cost) by (node) * 24 * 30\n) +\n\n\n# Memory\nsum(\n  avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * 24 * 30\n) +\n\n# Storage \n\nsum(avg(pv_hourly_cost) by (persistentvolume) * 24 * 30 * avg(kube_persistentvolume_capacity_bytes) by (persistentvolume) / 1024 / 1024 / 1024) \n+\n(sum(sum(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}) by (instance) / 1024 / 1024 / 1024) * on() vector(0))",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Top 20 by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk( 20, \n  sum(sum(container_memory_allocation_bytes) by (namespace,instance) * on(instance) group_left() (\n\t\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024 * 730\n\t\t\t\t+ on(node,instance_type) group_left()\n\t\t\t\t\tlabel_replace\n\t\t\t\t\t(\n\t\t\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t\t\t) * 0\n\t\t\t)\n  + \n  sum(container_cpu_allocation) by (namespace,instance) * on(instance) group_left() (\n\t  \t\t\tnode_cpu_hourly_cost{} + on(node,instance_type) group_left()\n\t\t  \t\t\tlabel_replace\n\t\t  \t\t\t(\n\t\t  \t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t  \t\t\t) * 0\n\t\t  \t) * 24 * 30) by (namespace)\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n ) \n / \n (sum (kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"}))\n) * 100",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"}) * 100",
     "legendFormat": "ram"
    },
    {
     "expr": "sum (\n sum(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(pod_pvc_allocation) by (persistentvolumeclaim, namespace) or up * 0\n + sum(container_fs_usage_bytes{device!=\"tmpfs\",id=\"/\"})\n) /\nsum (\n sum(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or up * 0\n + sum(container_fs_limit_bytes{device!=\"tmpfs\",id=\"/\"})\n) * 100",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "Utilized cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  avg(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}) by (node) * avg(node_cpu_hourly_cost) by (node) * 24 * 30\n)\n*\n(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n ) \n / \n (sum (kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"}))\n)",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(\n  avg(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}) by (node) / 1024 / 1024 / 1024 * avg(node_ram_hourly_cost) by (node) * 24 * 30\n)\n*\nsum(container_memory_working_set_bytes{namespace!=\"\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "ram"
    },
    {
     "expr": "(sum(avg(pv_hourly_cost) by (persistentvolume) * 24 * 30 * avg(kube_persistentvolume_capacity_bytes) by (persistentvolume) / 1024 / 1024 / 1024) \n+\n(sum(sum(container_fs_limit_bytes{device!=\"tmpfs\", id=\"/\"}) by (instance) / 1024 / 1024 / 1024) * on() vector(0)))\n*\nsum (\n sum(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(pod_pvc_allocation) by (persistentvolumeclaim, namespace) or up * 0\n + sum(container_fs_usage_bytes{device!=\"tmpfs\",id=\"/\"})\n) /\nsum (\n sum(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, namespace)\n + on (persistentvolumeclaim, namespace)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or up * 0\n + sum(container_fs_limit_bytes{device!=\"tmpfs\",id=\"/\"})\n)",
     "legendFormat": "storage"
    }
   ]
  }
 ]
}